CREATE TABLE users (
  user_id VARCHAR NOT NULL PRIMARY KEY,
  username VARCHAR NOT NULL
);

CREATE TABLE posts (
  id SERIAL PRIMARY KEY,
  user_id VARCHAR NOT NULL REFERENCES users,
  title VARCHAR NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
