CREATE TABLE users (
  user_id VARCHAR NOT NULL PRIMARY KEY,
  picture VARCHAR,
  name VARCHAR NOT NULL
);

CREATE TABLE posts (
  post_id SERIAL PRIMARY KEY,
  user_id VARCHAR NOT NULL REFERENCES users,
  title VARCHAR NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
